service: emojibot

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*

functions:
  install:
    handler: src/handler.install
    environment:
      CLIENT_ID: ${file(local.yml):slack.clientId}
    events:
      - http: GET install
  authorized:
    handler: src/handler.authorized
    environment:
      CLIENT_ID: ${file(local.yml):slack.clientId}
      CLIENT_SECRET: ${file(local.yml):slack.clientSecret}
    events:
      - http: GET authorized
  event:
    handler: src/handler.event
    events:
      - http: POST event

resources:
  Resources:
    accessTokenTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: accessTokenTable
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
